replicaCount: 2

image:
  repository: priyakirana14/hospital
  tag: latest

service:
  port: 80
  targetPort: 5000

config:
  ADMIN_USERNAME: admin
  MONGO_URI: mongodb://mongo:27017/hospital_management

secret:
  ADMIN_PASSWORD: 10@AdminPW
  SESSION_SECRET: yourSuperSecretSessionKey
  JWT_SECRET: yourSuperSecretJWTKey123456789

